import VersoManual
import Std.Time

namespace SFLMeta

/-!
Every generated `.lean` chapter and HTML pages records a build stamp.
The top-level build captures it once in `SFL_BUILD_STAMP` environment variable
(set via `BUILD_STAMP` in Makefile) so all volumes and variants share it.
A volume executable computes it directly if it runs on its own.
Only Lean files generated by Verso are stamped —
directly copied files such as `SFLCompat` and `CustomTacitcs` are unchanged.
-/

private def git (args : Array String)
    (env : Array (String × Option String) := #[]) : IO String := do
  let out ← IO.Process.output { cmd := "git", args, env }
  if out.exitCode != 0 then
    throw <| IO.userError s!"Git command failed:\n{out.stderr}"
  return out.stdout.trimAscii.toString

open Std.Time TimeZone in
/-- Compute source provenance from the current Git checkout. -/
def computeBuildStamp : IO String := do
  let revision ← git #["rev-parse", "HEAD"]
  let committed ← git #["show", "-s", "--date=format-local:%Y-%m-%d %H:%M UTC",
    "--format=%cd", "HEAD"] #[
      ("TZ", some "UTC")
    ]
  let status ← git #["status", "--porcelain=v1", "--untracked-files=normal"]
  let source := s!"Source {revision}, committed {committed}"
  if status.isEmpty then
    return source
  let now ← Timestamp.now
  let utc := DateTime.ofTimestamp now <| ZoneRules.ofTimeZone UTC
  return s!"{source}; uncommitted changes; built {utc.format "yyyy-MM-dd HH:mm"} UTC"

/-- Use the build-wide stamp when supplied, computing one for direct runs. -/
def buildStamp : IO String := do
  if let some inherited ← IO.getEnv "SFL_BUILD_STAMP" then
    let inherited := inherited.trimAscii.toString
    if !inherited.isEmpty then
      return inherited
  computeBuildStamp

/-- `body`, with `stamp` appended as a trailing comment.  Trailing whitespace is
trimmed first so the stamp always sits one blank line below the last line of
code, however the emitter happened to end. -/
def withBuildStamp (stamp body : String) : String :=
  body.trimAsciiEnd.toString ++ "\n\n-- " ++ stamp ++ "\n"

/-- `stamp` as the last line of an HTML page, styled by `.sf-build-stamp` in
`SFLMeta.sfTheme`.  Wired in through `Config.extraContents`, which puts it after
the page contents (just above the navigation buttons). -/
def buildStampHtml (stamp : String) : Verso.Output.Html :=
  open Verso.Output.Html in
  {{<div class="sf-build-stamp">{{stamp}}</div>}}

end SFLMeta
