-- This file was generated by Codex.
import VersoManual
import SFLMeta.Volume

open Lean Verso Doc Genre Manual

namespace SFLMeta

/-- The two directory layouts used for the books' HTML. -/
inductive HtmlLayout where
  /-- `_out/<volume>/<mode>/html/`, also used by branch previews. -/
  | build
  /-- `<release>/<volume>/html/`, produced by `package_release.py`. -/
  | release

private def HtmlLayout.volumeRoot (layout : HtmlLayout) (vol mode : String) : Multi.Path :=
  match layout with
  | .build => #["..", "..", "..", vol, mode, "html"]
  | .release => #["..", "..", vol, "html"]

/-- Resolve references such as `{ref "Typeclasses" (remote := "lf")}[Typeclasses]`
against the prerequisite chapters supplied to `runVolume`.

Each group is traversed as children of a volume root, just as in the actual book.
Verso therefore supplies the destination paths and anchors, including explicit
`file` metadata. The resulting links are relative to the current HTML root so
they also work when a preview or release is hosted under a URL prefix. -/
def crossVolumeExtensions (chapters : List (String × Part Manual))
    (mode : String) (layout : HtmlLayout) (config : Config) : EmitM ExtensionImpls := do
  let impls ← read
  if chapters.isEmpty then return impls
  let some refDescr := impls.getInline? ``Manual.Inline.ref
    | throw <| IO.userError "Missing Verso reference extension"
  let mut groups : Array (String × Array (Part Manual)) := #[]
  for (vol, chapter) in chapters do
    let vol := vol.toLower
    if let some i := groups.findIdx? (·.1 == vol) then
      groups := groups.modify i fun (v, parts) => (v, parts.push chapter)
    else
      groups := groups.push (vol, #[chapter])
  let mut targets : Array (String × TraverseState) := #[]
  for (vol, parts) in groups do
    let title := (volumeBySlug? vol).map (·.name) |>.getD vol
    let root : Part Manual := .mk #[.text title] title none #[] parts
    let (_, state) ← traverse root config
    targets := targets.push (vol, state)
  return impls.insertInline ``Manual.Inline.ref { refDescr with
    traverse := fun id info content => do
      if let .ok (some remote) := info.getObjValAs? (Option String) "remote" then
        if let some (vol, state) := targets.find? (·.1 == remote) then
          let .ok name := info.getObjValAs? String "canonicalName"
            | return ← refDescr.traverse id info content
          let .ok domain := info.getObjValAs? (Option Name) "domain"
            | return ← refDescr.traverse id info content
          let domain := domain.getD sectionDomain
          match state.resolveDomainObject domain name with
          | .error _ =>
            -- Prerequisites cover only part of a book. Its configured remote
            -- index may supply the remaining chapters.
            return ← refDescr.traverse id info content
          | .ok dest =>
            let dest := { dest with path := layout.volumeRoot vol mode ++ dest.path }
            -- Clear `remote` so Verso relativizes the link for each source page.
            return some <| .other (Manual.Inline.ref name (some domain) none (some dest)) content
      refDescr.traverse id info content
  }

/-- Apply the traversal options before indexing prerequisite chapters.

Verso's command-line parser is private. Keep this scan limited to the options
that affect reference destinations, skipping the arguments of its other
value-taking options. `manualMain` still parses and validates the full list. -/
private def referenceConfig (config : Config) : List String → Config
  | "--depth" :: depth :: more =>
    referenceConfig { config with htmlDepth := depth.toNat! } more
  | "--draft" :: more => referenceConfig { config with draft := true } more
  | option :: value :: more =>
    if ["--output", "--remote-config", "--with-word-count",
        "--delay-html-single", "--resume-html-single",
        "--delay-html-multi", "--resume-html-multi"].contains option then
      referenceConfig config more
    else
      referenceConfig config (value :: more)
  | _ => config

/-- Render a volume with references to its prerequisite chapters.

The prerequisite index uses the same depth and draft settings as this build.
Pass the same rendering options when building the destination volumes. -/
def crossVolumeMain (doc : Part Manual) (chapters : List (String × Part Manual))
    (mode : String) (layout : HtmlLayout) (options : List String) (config : RenderConfig)
    (extensionImpls : ExtensionImpls := by exact extension_impls%)
    (extraSteps : List ExtraStep := []) : IO UInt32 := do
  let logger ← Logger.new
  let impls ← crossVolumeExtensions chapters mode layout (referenceConfig config.toConfig options)
    |>.run extensionImpls |>.run logger
  let rc ← logger.failIfErrors
  if rc != 0 then return rc
  manualMain doc (extensionImpls := impls) (options := options)
    (config := config) (extraSteps := extraSteps)

end SFLMeta
