-- This file was generated by Claude (Opus 5) and reviewed by hand.
import VersoManual
import SFLMeta.Volume

open Lean Elab
open Verso ArgParse Doc Elab Genre.Manual

namespace SFLMeta

/-!
# Version and volume variables

Version numbers, volume numbers, and volume titles are *build* facts, not prose:
they are recorded once in `lakefile.toml` (and, for titles and numbers, in the
`volumes` table of `SFLMeta/Volume.lean`) and reach the text through the roles
defined below.  Nothing in a chapter ever spells one out by hand, so a quoted
version or volume number cannot drift out of date.

`weak.`-prefixed options are ignored rather than rejected by a build that does
not go through Lake, which is why the lakefile sets them that way.
-/

/-- The release version of the SFL sources, e.g. `"0.1.0"`.  Set from
`[leanOptions] weak.sfl.version` in `lakefile.toml`, where it is kept in step
with the package's own `version` field. -/
register_option sfl.version : String := {
  defValue := ""
  descr := "Release version of the SFL sources (from lakefile.toml's [leanOptions] weak.sfl.version)"
}

/-- The release year of the SFL sources, e.g. `2026`.  Set from `[leanOptions]
weak.sfl.year` in `lakefile.toml`.  It is deliberately a recorded release fact
rather than the wall-clock year: two builds of the same tag must agree, and a
citation should name the year the edition was published. -/
register_option sfl.year : Nat := {
  defValue := 0
  descr := "Release year of the SFL sources (from lakefile.toml's [leanOptions] weak.sfl.year)"
}

/-- The slug of the volume currently being compiled (`"lf"`, `"ts"`, `"hl"`).
Set per library by `leanOptions` on each `[[lean_lib]]` in `lakefile.toml`,
*not* by anything a chapter imports — chapters shared between volumes are the
same source file (`HL/Slang.lean` ↔ `TS/Slang.lean` are symlinked), so the
library doing the compiling is the only thing that can tell them apart. -/
register_option sfl.volume : String := {
  defValue := ""
  descr := "Slug of the volume being compiled: lf, ts, or hl (set per lean_lib in lakefile.toml)"
}

/-- The release version, or an error naming the option to set. -/
def getSflVersion : DocElabM String := do
  let v := sfl.version.get (← getOptions)
  if v.isEmpty then
    throwError "option `sfl.version` is unset — add `weak.sfl.version = \"<version>\"` \
      under `[leanOptions]` in lakefile.toml"
  return v

/-- The release year, or an error naming the option to set. -/
def getSflYear : DocElabM Nat := do
  let y := sfl.year.get (← getOptions)
  if y == 0 then
    throwError "option `sfl.year` is unset — add `weak.sfl.year = <year>` \
      under `[leanOptions]` in lakefile.toml"
  return y

/-- The volume currently being compiled, from the `sfl.volume` option. -/
def getCurrVolume : DocElabM Volume := do
  let slug := sfl.volume.get (← getOptions)
  if slug.isEmpty then
    throwError "option `sfl.volume` is unset — give this chapter's `[[lean_lib]]` \
      in lakefile.toml a `leanOptions = \{ weak.sfl.volume = \"<slug>\" }` \
      (one of: {volumeSlugs})"
  let some vol := volumeBySlug? slug
    | throwError "unknown volume slug {slug} in option `sfl.volume` (expected one of: {volumeSlugs})"
  return vol

/-- Author-facing selector for the volume roles.  With no argument a role means
*the volume being compiled*; with a slug (`{volumeName "ts"}[]`) or a number
(`{volumeName 2}[]`) it means that other volume, which is how one volume refers
to another. -/
structure VolumeArgs where
  /-- A volume slug, as a string literal: `"lf"`, `"ts"`, `"hl"`. -/
  slug : Option String
  /-- A volume number, as a numeric literal: `1`, `2`, `3`. -/
  number : Option Nat
deriving Repr

section
variable [Monad m] [MonadError m]

def VolumeArgs.parse : ArgParse m VolumeArgs :=
  VolumeArgs.mk
    <$> ((some <$> ArgParse.positional `volume ValDesc.string) <|> Pure.pure none)
    <*> ((some <$> ArgParse.positional `volume ValDesc.nat) <|> Pure.pure none)

instance : FromArgs VolumeArgs m := ⟨VolumeArgs.parse⟩

end

/-- Resolve a role's optional volume selector, defaulting to the volume being
compiled. -/
def VolumeArgs.resolve : VolumeArgs → DocElabM Volume
  | ⟨some slug, _⟩ => do
    let some vol := volumeBySlug? slug
      | throwError "unknown volume {slug} (expected one of: {volumeSlugs})"
    return vol
  | ⟨none, some n⟩ => do
    let some vol := volumeByNumber? n
      | throwError "no volume numbered {n}"
    return vol
  | ⟨none, none⟩ => getCurrVolume

/-! ## Roles

* `{leanVersion}[]` — the Lean toolchain the book was built with.
* `{sflVersion}[]` — the release version of the book sources.
* `{sflYear}[]` — the release year of the book sources.
* `{volumeNumber}[]`, `{volumeName}[]` — this volume, or (given a slug or
  number) another one.

Any content written in the brackets is ignored; the value always comes from the
build. -/

@[role]
def leanVersion : RoleExpanderOf Unit
  | (), _ =>
    ``(Verso.Doc.Inline.code $(quote Lean.versionString))

@[role]
def sflVersion : RoleExpanderOf Unit
  | (), _ => do
    ``(Verso.Doc.Inline.code $(quote (← getSflVersion)))

@[role]
def sflYear : RoleExpanderOf Unit
  | (), _ => do
    ``(Verso.Doc.Inline.text $(quote (toString (← getSflYear))))

@[role]
def volumeNumber : RoleExpanderOf VolumeArgs
  | args, _ => do
    let vol ← args.resolve
    ``(Verso.Doc.Inline.text $(quote (toString vol.number)))

@[role]
def volumeName : RoleExpanderOf VolumeArgs
  | args, _ => do
    let vol ← args.resolve
    ``(Verso.Doc.Inline.text $(quote vol.name))

/-- The BibTeX entry for a volume, built from the volume table and the release
version and year.  A citation is entirely mechanical, and a hand-written one
goes stale the moment a version is cut, so the text of the entry lives here
rather than in each Preface. -/
def bibtexEntry (vol : Volume) (version : String) (year : Nat) : String :=
  String.intercalate "\n"
    [ "@book            {SFL:" ++ toString vol.number ++ ",",
      "author       =   {Mike Hicks and Benjamin C. Pierce and the SF-in-Lean team},",
      "title        =   \"" ++ vol.name ++ "\",",
      "series       =   \"Software Foundations in Lean\",",
      "volume       =   \"" ++ toString vol.number ++ "\",",
      "year         =   \"" ++ toString year ++ "\",",
      "publisher    =   \"Electronic textbook\",",
      "note         =   {Version " ++ version ++ ", \\URL<" ++ sflHomepage ++ ">}",
      "}" ]

/-- `:::citation` emits the recommended citation for the volume being compiled
(or, given a slug or number, for another volume) as a code block. -/
@[directive]
def citation : DirectiveExpanderOf VolumeArgs
  | args, _ => do
    let vol ← args.resolve
    let entry := bibtexEntry vol (← getSflVersion) (← getSflYear)
    ``(Verso.Doc.Block.code $(quote entry))

end SFLMeta
