-- This file was generated by Claude (Opus 5) and reviewed by hand.
import VersoManual

open Lean

namespace SFLMeta

/-- Identity of one volume of *Software Foundations in Lean*.

`slug` is the lowercase identifier used everywhere a volume has to be named
mechanically: the `lean_lib`/`lean_exe` names (`LF`, `sfl-lf`), the `_out/<slug>/…`
build directory, the `weak.sfl.volume` option each library sets, and the volume
prefix handed to the saver by `runVolume`.  `number` is the volume's place in
the reading order, and `name` is its title as it appears on the cover and in a
citation. -/
structure Volume where
  slug : String
  number : Nat
  name : String
deriving Repr, Inhabited, BEq

/-- Every volume of the series, in reading order.  This table is the single
source of truth for volume numbers and titles: prose gets at it through the
`{volumeNumber}[]` / `{volumeName}[]` roles (see `SFLMeta/Version.lean`), which
means no chapter ever spells a volume number or title out by hand. -/
def volumes : List Volume :=
  [ { slug := "lf", number := 1, name := "Logical Foundations" },
    { slug := "ts", number := 2, name := "Type Systems" },
    { slug := "hl", number := 3, name := "Hoare Logic" } ]

/-- Look a volume up by its slug (`"lf"`, `"ts"`, `"hl"`), case-insensitively. -/
def volumeBySlug? (slug : String) : Option Volume :=
  volumes.find? (·.slug == slug.toLower)

/-- Look a volume up by its number (1, 2, 3). -/
def volumeByNumber? (n : Nat) : Option Volume :=
  volumes.find? (·.number == n)

/-- Where the series lives.  Used in the recommended citation (`:::citation`),
so that a URL, like a version number, is written down in exactly one place. -/
def sflHomepage : String := "https://github.com/plclub/sf-in-lean"

/-- The slugs of all volumes, for error messages. -/
def volumeSlugs : String :=
  String.intercalate ", " (volumes.map (·.slug))

end SFLMeta
