#!/usr/bin/env python3
# This file was generated by Claude.
"""
Check that structural markers in a code-forward `.lean` source were actually
*translated* into the Verso output — not silently flattened away.

Motivation
----------
`check_verso_prose.py` compares contiguous runs of *words*, so it catches lost
prose.  It is, by design, blind to lost *markup*: when to_verso deletes a
region marker and lets the surrounding prose render as ordinary paragraphs, no
words disappear and the prose check passes green.  That is exactly how the
`-- QUIZ` bug slipped through — the quiz question text survived verbatim while
the quiz *structure* was dropped, because `QUIZ` sat in to_verso's
`_DROP_MARKER_RE` with no corresponding Verso construct.

This check closes that blind spot.  It inventories the structural markers in the
source and, for each marker that is *supposed* to become a Verso directive,
verifies that the expected directive appears in the translation.  A marker that
occurs in the source but produces none of its expected construct is a silent
flattening and is reported (exit status 1).

Method
------
1. Count marker *opens* in the source (line form `-- MARKER`, single-line block
   form `/- MARKER -/`, and bare `MARKER` lines inside a `/- … -/` body — the
   last is the form `_DROP_MARKER_RE` swallows).
2. For each marker in POLICY:
     * a truthy `expect` pattern means "must produce this directive": FAIL if the
       source has >=1 open but the output contains none of it.
     * `expect is None` means "intentionally dropped, content preserved" (e.g.
       ADMITTED stays a Lean comment): never fails, reported only under -v.
3. A count mismatch (fewer directives than source opens, but not zero) is a soft
   WARNING, not a failure — legitimate fence bookkeeping (e.g. :::full re-arming,
   exercises closing implicitly at a heading) can make exact counts diverge.

Any marker keyword found in the source that is absent from POLICY is itself a
FAILURE ("unclassified marker"): it forces a human to decide whether a newly
introduced marker should be translated or dropped, rather than defaulting to a
silent drop.

Usage
-----
  check_verso_markers.py SOURCE.lean VERSO.lean [-v]

Exit status is 1 if any silent flattening or unclassified marker is found.
"""
from __future__ import annotations

import argparse
import re
import sys
from typing import Optional

# marker -> regex the translation must contain when the marker is present.
#   expect = a pattern  -> must be translated to that construct
#   expect = None       -> intentionally dropped (content preserved elsewhere)
# `opens` is the pattern that recognizes an *opening* marker in the source; it is
# matched against the marker keyword alone (prefix `--`, `/-`, and `/…` closers
# are stripped before matching, so `-- QUIZ`, `/- QUIZ -/`, `QUIZ`, and the
# closing `-- /QUIZ` all reduce to the keyword `QUIZ`).
_POLICY = [
    # keyword regex          expect (output construct) / None
    ("FULL",                 r"::+full\b"),
    ("TERSE",                r"::+(?:terse|slidebreak)\b"),
    ("EX\\d+[A-Za-z!?]*",    r"::+exercise\b"),
    ("GRADE_\\w+",           r":::grade\b"),
    # `-- INSTRUCTORS:` notes -> :::instructors; a bare `-- INSTRUCTORS` region
    # is a hidden region (-> ::::hide, or :::answer inside a quiz).
    ("INSTRUCTORS",          r":::instructors\b|::+hide\b|:::answer\b"),
    # A SOLUTION is one of two things: a *compilable* answer becomes the in-code
    # `solution!` / `-- SOLUTION` form SFLMeta rewrites; a *prose* answer becomes
    # a :::solution directive.  Either counts as translated.  QUIETSOLUTION (a
    # solution shown without the solutions-build banner) is handled identically.
    ("SOLUTION",             r":::solution\b|solution!|-- SOLUTION\b"),
    ("QUIETSOLUTION",        r":::solution\b|solution!|-- SOLUTION\b"),
    # HIDE normally -> ::::hide, but a HIDE *inside* a QUIZ is the quiz's answer
    # -> :::answer, so both count as a translated HIDE.
    ("HIDE",                 r"::+hide\b|:::answer\b"),
    ("QUIZ",                 r"::+quiz\b"),
    # `-- DEV` … `-- /DEV` region: an untagged author/dev note -> :::dev.
    ("DEV",                  r":::dev\b"),
    # Intentionally dropped: region semantics not honored, prose kept as-is.
    ("HIDEFROMHTML",         None),
    # FOLD marks a proof region to render collapsed; folding is not honored
    # yet — markers dropped, content kept (same policy as HIDEFROM*).
    ("FOLD",                 None),
    ("HIDEFROMADVANCED",     None),
    # WORKINCLASS regions become `workinclass!` tactic blocks (proof shown in
    # student/solutions, `sorry` in terse).  A WORKINCLASS paired with an
    # ADMITTED region collapses into that region's `solution!` (which already
    # stubs the terse build), and the markers of a *narrative* region (body
    # containing rendered prose) are dropped — so counts may legitimately fall
    # short of the source tally (soft WARN, verify by hand).
    ("WORKINCLASS",          r"workinclass!|solution!"),
    # Left as Lean comments inside the code block; the code itself is preserved.
    ("ADMITTED",             None),
    ("ADMITDEF",             None),
]

# Author / developer notes -> :::dev directives.  Matched separately because
# the keyword is an author initial or task word, not a region name.
_AUTHOR_KEYWORDS = ("BCP", "JC", "MWH", "CGH", "RAB", "CH", "HG", "NB", "MMG",
                    "APT", "DHS", "TODO", "TOFIX", "LATER", "SOONER")
_AUTHOR_EXPECT = r":::dev\b"

# A line reduces to a "marker keyword" candidate if, after stripping a leading
# `--` line-comment prefix or a `/-`/`-/` block-comment fence and an optional
# `/` region-closer, what remains *begins* with an uppercase-marker token.
_KEYWORD_RE = re.compile(r"^/?([A-Z][A-Z0-9_]*(?:\d+[A-Za-z!?]*)?)")


def _marker_candidates(text: str):
    """Yield `(keyword, is_close)` for every line that looks like a structural
    marker (line-comment, single-line block, or bare-in-block form).  A closing
    marker (`/QUIZ`) yields the same keyword as its open with `is_close=True`, so
    it counts toward "known" markers but not toward the open tally."""
    for raw in text.splitlines():
        s = raw.strip()
        if not s:
            continue
        # Strip a block-comment fence: `/- MARKER -/` or `/- MARKER`.
        if s.startswith("/-") and not s.startswith("/--") and not s.startswith("/-!"):
            s = s[2:].strip()
            if s.endswith("-/"):
                s = s[:-2].strip()
        # Strip a `-- ` line-comment prefix.
        elif s.startswith("--"):
            s = s[2:].strip()
        # else: a bare line inside a block-comment body (e.g. `-- /QUIZ` already
        # handled above; `QUIZ` on its own line handled here).
        is_close = s.startswith("/")
        m = _KEYWORD_RE.match(s)
        if m:
            yield m.group(1), is_close


def _count_opens(candidates, keyword_re: str) -> int:
    pat = re.compile(r"^(?:%s)$" % keyword_re)
    return sum(1 for k, is_close in candidates if not is_close and pat.match(k))


def _count_construct(dst: str, expect: str) -> int:
    return len(re.findall(expect, dst))


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("source")
    ap.add_argument("verso")
    ap.add_argument("-v", "--verbose", action="store_true",
                    help="also report markers that were correctly translated "
                         "or intentionally dropped")
    args = ap.parse_args()

    src = open(args.source).read()
    dst = open(args.verso).read()
    candidates = list(_marker_candidates(src))
    known = set()
    failures = 0
    warnings = 0

    def report(status, kw, msg):
        print(f"{status:7} {kw:18} {msg}")

    for keyword_re, expect in _POLICY:
        opens = _count_opens(candidates, keyword_re)
        # Record every literal keyword this policy entry recognizes as "known".
        for k, _ in candidates:
            if re.match(r"^(?:%s)$" % keyword_re, k):
                known.add(k)
        if opens == 0:
            continue
        if expect is None:
            if args.verbose:
                report("DROP", keyword_re, f"{opens} in source (intentionally dropped)")
            continue
        got = _count_construct(dst, expect)
        if got == 0:
            failures += 1
            report("FLATTENED", keyword_re,
                   f"{opens} in source but 0 `{expect}` in output "
                   f"— marker silently dropped, not translated")
        elif got < opens:
            warnings += 1
            report("WARN", keyword_re,
                   f"{opens} in source but only {got} `{expect}` in output "
                   f"(count mismatch — verify by hand)")
        elif args.verbose:
            report("OK", keyword_re, f"{opens} in source, {got} in output")

    # Author / developer notes.  Match to_verso's actual trigger (_AUTHOR_RE):
    # the keyword must be followed by `:`, ` (`, or a space — a bare `-- CH`
    # or a word that merely *starts* with an initial is not an author note.
    author_alt = "|".join(_AUTHOR_KEYWORDS)
    author_note_re = re.compile(
        r"^\s*(?:--|/-)\s*(?:%s)[: (]" % author_alt)
    author_opens = sum(1 for raw in src.splitlines()
                       if author_note_re.match(raw))
    if author_opens:
        got = _count_construct(dst, _AUTHOR_EXPECT)
        if got == 0:
            failures += 1
            report("FLATTENED", "author-note",
                   f"{author_opens} in source but 0 `{_AUTHOR_EXPECT}` in output")
        elif args.verbose:
            report("OK", "author-note", f"{author_opens} in source, {got} in output")

    # Any leading-uppercase keyword we saw but never classified is a marker we
    # don't have a policy for.  Only flag ones that plausibly *are* markers: they
    # appear as a standalone marker line (`-- FOO`, `/- FOO -/`, or `/FOO`).
    unclassified = {}
    marker_line_re = re.compile(
        r"^\s*(?:--\s*/?([A-Z][A-Z0-9_]*)\s*$"
        r"|/-\s*/?([A-Z][A-Z0-9_]*)\s*-/\s*$)")
    for raw in src.splitlines():
        m = marker_line_re.match(raw)
        if not m:
            continue
        kw = m.group(1) or m.group(2)
        if kw and kw not in known and kw not in _AUTHOR_KEYWORDS:
            unclassified[kw] = unclassified.get(kw, 0) + 1
    for kw, cnt in sorted(unclassified.items()):
        failures += 1
        report("UNKNOWN", kw,
               f"{cnt} standalone marker line(s), not in POLICY "
               f"— classify it (translate or drop) in check_verso_markers.py")

    print()
    print(f"{failures} silent-flattening / unclassified failure(s), "
          f"{warnings} warning(s) in {args.source}")
    return 1 if failures else 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except BrokenPipeError:
        sys.exit(0)
