#!/usr/bin/env python3
# This file was generated by Claude.
"""
package_release.py — Package a "local release" of SF-in-Lean for the course
webpage: the student-facing html/ and lean/ for each volume, nothing else.

For each requested volume (lf / hl / ts):

  1. Optionally restrict the volume to an allow-listed subset of chapters
     (config: scripts/release_chapters.json). Every *other* chapter currently
     imported by <VOL>.lean stays part of the book — so it still gets an HTML
     page and a nav/TOC entry, and any `{ref "Chapter"}[...]` link to it from a
     kept chapter still resolves — but its source is temporarily swapped for a
     one-line "under construction" placeholder. The original chapter files are
     always restored afterward, however the build turns out.
  2. Build the student variant (`lake exe sfl-<vol> student`), which emits
     _out/<vol>/student/{html,lean}.
  3. Delete the placeholder chapters' generated `.lean` files (and their
     `import` lines from the generated project's own <VOL>.lean) from that
     output — an excluded chapter gets an "under construction" page in html/,
     but no file at all in lean/.
  4. Scan the surviving output for leaked developer-facing material: a
     `:::dev` note only ever reaches the student build at all if it's marked
     `NOW`-urgency (see SFLMeta/Comment.lean), rendered as
     `class="sf-dev-note"` in html and `-- Note to developers` in lean; a raw
     `:::dev`/`:::instructors` string surviving verbatim would mean a Verso
     parse escape. Any hit blocks that volume's release (fix/hide the note and
     rerun) unless --allow-dev-notes.
  5. Copy the clean html/ and lean/ into <out>/<vol>/html and
     <out>/<vol>/sf-<vol>-lean, stripping the .lake build cache from the lean
     copy (source-only, like SF's old .v releases) unless --keep-lake, and zip
     the lean directory up as <out>/<vol>/sf-<vol>-lean.zip.

Usage:
  python3 scripts/package_release.py [--volumes lf,hl,ts] [--out release]
      [--config scripts/release_chapters.json] [--allow-dev-notes] [--keep-lake]
"""

import argparse
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
ALL_VOLUMES = ["lf", "hl", "ts"]

DEV_NOTE_HTML_MARKER = 'class="sf-dev-note"'
DEV_NOTE_LEAN_RE = re.compile(r"^\s*--\s*Note to developers")
RAW_LEAK_MARKERS = [":::dev", ":::instructors"]

PLACEHOLDER_MESSAGE = "This chapter is under construction and not yet available in this release."
CHAPTER_TITLE_RE = re.compile(r'#doc \(Manual\) "([^"]*)" =>')


def chapter_import_re(vol_upper):
    return re.compile(rf"^import {vol_upper}\.(\w+)\s*$", re.MULTILINE)


def list_chapters(vol):
    """Ordered chapter names (module suffixes) imported by <VOL>.lean."""
    vol_upper = vol.upper()
    text = (REPO_ROOT / f"{vol_upper}.lean").read_text()
    return chapter_import_re(vol_upper).findall(text)


def placeholder_chapter_text(original_text, chapter_name):
    """A minimal replacement chapter: same title (for a readable nav entry)
    and a tag/file set to `chapter_name`, so `{ref "chapter_name"}` links from
    kept chapters keep resolving and the generated lean filename is
    predictable (see strip_excluded_from_lean_output)."""
    m = CHAPTER_TITLE_RE.search(original_text)
    title = m.group(1) if m else chapter_name
    return f'''import SFLMeta

open Verso.Genre Manual
open SFLMeta

#doc (Manual) "{title}" =>
%%%
tag := "{chapter_name}"
htmlSplit := .never
file := some "{chapter_name}"
%%%

{PLACEHOLDER_MESSAGE}
'''


def warn_on_excluded_deps(vol, keep, excluded):
    """A kept chapter that itself `import`s an excluded chapter would lose
    real definitions it depends on (the excluded chapter is now a placeholder
    with no content) — flag it; the allow-list needs to include prerequisites."""
    vol_upper = vol.upper()
    excluded_set = set(excluded)
    for c in keep:
        text = (REPO_ROOT / vol_upper / f"{c}.lean").read_text()
        deps = set(chapter_import_re(vol_upper).findall(text)) & excluded_set
        if deps:
            print(f"WARNING: kept chapter {c} imports excluded chapter(s) {sorted(deps)}; "
                  "it will be missing real definitions it depends on")


def git_path_is_clean(path):
    """True if `path` (file or directory) has no uncommitted changes,
    staged or not."""
    rel = path.relative_to(REPO_ROOT)
    for staged in (False, True):
        cmd = ["git", "diff", "--quiet"]
        if staged:
            cmd.append("--cached")
        cmd += ["--", str(rel)]
        if subprocess.run(cmd, cwd=REPO_ROOT).returncode != 0:
            return False
    return True


def build_student(vol):
    subprocess.run(["scripts/relocate-lake-build.sh"], cwd=REPO_ROOT, check=True)
    subprocess.run(["lake", "build", f"sfl-{vol}"], cwd=REPO_ROOT, check=True)
    subprocess.run(["lake", "exe", f"sfl-{vol}", "student"], cwd=REPO_ROOT, check=True)


def strip_excluded_from_lean_output(vol, excluded):
    """Remove the placeholder chapters' generated .lean files and their
    import lines from the generated project's own <VOL>.lean, so they leave no
    trace in the packaged lean/ directory at all."""
    if not excluded:
        return
    vol_upper = vol.upper()
    lean_dir = REPO_ROOT / f"_out/{vol}/student/lean"
    for c in excluded:
        f = lean_dir / vol_upper / f"{c}.lean"
        f.unlink(missing_ok=True)
    root = lean_dir / f"{vol_upper}.lean"
    alt = "|".join(re.escape(c) for c in excluded)
    pat = re.compile(rf"^import {vol_upper}\.(?:{alt})\s*\n", re.MULTILINE)
    root.write_text(pat.sub("", root.read_text()))


def scan_for_leaks(vol):
    """Return a list of (relpath, lineno, snippet) for any developer-facing
    material found in the built student output."""
    hits = []
    html_dir = REPO_ROOT / f"_out/{vol}/student/html"
    lean_dir = REPO_ROOT / f"_out/{vol}/student/lean"

    for f in sorted(html_dir.rglob("*.html")):
        for i, line in enumerate(f.read_text(errors="replace").splitlines(), 1):
            if DEV_NOTE_HTML_MARKER in line or any(m in line for m in RAW_LEAK_MARKERS):
                hits.append((f.relative_to(REPO_ROOT), i, line.strip()[:120]))

    for f in sorted(lean_dir.rglob("*.lean")):
        for i, line in enumerate(f.read_text(errors="replace").splitlines(), 1):
            if DEV_NOTE_LEAN_RE.match(line) or any(m in line for m in RAW_LEAK_MARKERS):
                hits.append((f.relative_to(REPO_ROOT), i, line.strip()[:120]))

    return hits


def copy_release(vol, out_dir, keep_lake):
    dest = out_dir / vol
    if dest.exists():
        shutil.rmtree(dest)
    shutil.copytree(REPO_ROOT / f"_out/{vol}/student/html", dest / "html")
    lean_name = f"sf-{vol}-lean"
    ignore = None if keep_lake else shutil.ignore_patterns(".lake")
    shutil.copytree(REPO_ROOT / f"_out/{vol}/student/lean", dest / lean_name, ignore=ignore)

    zip_path = shutil.make_archive(str(dest / lean_name), "zip", root_dir=dest, base_dir=lean_name)
    return dest, Path(zip_path)


def load_config(config_path):
    data = json.loads(config_path.read_text())
    return {k: v for k, v in data.items() if k in ALL_VOLUMES}


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--volumes", default=",".join(ALL_VOLUMES),
                     help="comma-separated subset of lf,hl,ts (default: all)")
    ap.add_argument("--out", default="release", help="release output directory (default: release/)")
    ap.add_argument("--config", default="scripts/release_chapters.json",
                     help="chapter allow-list config (default: scripts/release_chapters.json)")
    ap.add_argument("--allow-dev-notes", action="store_true",
                     help="copy the release even if leaked dev notes are found (still prints them)")
    ap.add_argument("--keep-lake", action="store_true",
                     help="keep the .lake build cache in the packaged lean/ directory")
    args = ap.parse_args()

    volumes = [v.strip() for v in args.volumes.split(",") if v.strip()]
    for v in volumes:
        if v not in ALL_VOLUMES:
            raise SystemExit(f"unknown volume '{v}'; expected one of {ALL_VOLUMES}")

    config_path = REPO_ROOT / args.config
    config = load_config(config_path) if config_path.exists() else {}
    out_dir = REPO_ROOT / args.out
    out_dir.mkdir(parents=True, exist_ok=True)

    results = []  # (vol, chapters_desc, status, detail)

    for vol in volumes:
        keep = config.get(vol)
        vol_upper = vol.upper()
        vol_dir = REPO_ROOT / vol_upper
        chapters_desc = ", ".join(keep) if keep else "all"
        print(f"\n=== {vol_upper}: chapters = {chapters_desc} ===")

        if not git_path_is_clean(vol_dir):
            results.append((vol, chapters_desc, "SKIPPED",
                             f"{vol_upper}/ has uncommitted changes; commit or stash before "
                             "packaging (the packager may rewrite excluded chapters' files "
                             "temporarily and restores them from the working tree afterward)"))
            print(results[-1][3])
            continue

        all_chapters = list_chapters(vol)
        unknown = [c for c in (keep or []) if c not in all_chapters]
        if unknown:
            raise SystemExit(
                f"release_chapters.json lists unknown {vol_upper} chapter(s) {unknown}; "
                f"chapters currently in {vol_upper}.lean: {all_chapters}"
            )
        excluded = [c for c in all_chapters if c not in keep] if keep else []
        if keep:
            warn_on_excluded_deps(vol, keep, excluded)

        backups = {}
        try:
            for c in excluded:
                f = vol_dir / f"{c}.lean"
                backups[f] = f.read_text()
                f.write_text(placeholder_chapter_text(backups[f], c))
            if excluded:
                print(f"placeholder'd {len(excluded)} excluded chapter(s): {excluded}")

            build_student(vol)
            strip_excluded_from_lean_output(vol, excluded)

            leaks = scan_for_leaks(vol)
            if leaks:
                print(f"BLOCKED: developer-facing material leaked into the student build for {vol_upper}:")
                for relpath, lineno, snippet in leaks:
                    print(f"  {relpath}:{lineno}: {snippet}")
                if not args.allow_dev_notes:
                    results.append((vol, chapters_desc, "BLOCKED", f"{len(leaks)} leak(s); see above"))
                    continue
                print("--allow-dev-notes set: copying anyway")

            dest, zip_path = copy_release(vol, out_dir, args.keep_lake)
            results.append((vol, chapters_desc, "OK", str(dest.relative_to(REPO_ROOT))))
            print(f"packaged -> {dest.relative_to(REPO_ROOT)} (lean zipped as {zip_path.relative_to(REPO_ROOT)})")

        finally:
            for f, text in backups.items():
                f.write_text(text)

    print("\n=== summary ===")
    blocked = False
    for vol, chapters_desc, status, detail in results:
        print(f"{vol.upper():3} [{chapters_desc:20}] {status:8} {detail}")
        if status != "OK":
            blocked = True

    return 1 if blocked else 0


if __name__ == "__main__":
    sys.exit(main())
