#!/usr/bin/env python3
# This file was generated by Codex.
"""Render fixtures and follow their cross-volume links in both published layouts.

Run from the repository root: python3 scripts/test_cross_volume.py
"""

from html.parser import HTMLParser
import json
from pathlib import Path
import subprocess
import tempfile
import unittest
from unittest.mock import patch
from urllib.parse import parse_qs, unquote, urljoin, urlsplit

import package_release

REPO_ROOT = Path(__file__).resolve().parent.parent


class Links(HTMLParser):
    def __init__(self, path):
        super().__init__()
        self.ids = set()
        self.links = {}
        self.anchor = None
        self.base = ""
        self.permalinks = []
        self.feed(path.read_text())

    def handle_starttag(self, tag, attrs):
        attrs = dict(attrs)
        if "id" in attrs:
            self.ids.add(attrs["id"])
        if tag == "base":
            self.base = attrs.get("href", "")
        if tag == "a":
            self.anchor = [attrs.get("href", ""), ""]
            if attrs.get("title") == "Permalink":
                query = parse_qs(urlsplit(attrs["href"]).query)
                self.permalinks.extend(query.get("name", []))

    def handle_data(self, data):
        if self.anchor is not None:
            self.anchor[1] += data

    def handle_endtag(self, tag):
        if tag == "a" and self.anchor is not None:
            href, text = self.anchor
            self.links[text] = href
            self.anchor = None


class CrossVolumeTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        subprocess.run(["lake", "build", "SFLMeta.Run"], cwd=REPO_ROOT, check=True)

    def render(self, out, mode="student", layout="build", test_case="valid", options=()):
        result = subprocess.run(
            ["lake", "env", "lean", "--run", "scripts/TestCrossVolume.lean",
             str(out), mode, layout, test_case, *options],
            cwd=REPO_ROOT, text=True, capture_output=True,
        )
        if test_case in ("valid", "fallback", "draft"):
            self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        return result

    def check_links(self, site, mode, release=False, depth=2, draft=False):
        # Simulate hosting below a branch/release prefix, not at the domain root.
        prefix = "https://example.invalid/course/previews/branch/"

        def html_dir(vol):
            return site / vol / "html" if release else site / vol / mode / "html"

        expected = {
            "cross-root": ("lf", "typeclasses-file", "Typeclasses"),
            "cross-poly": ("lf", "poly-file", "Poly"),
            "cross-types": ("ts", "types-file", "Types"),
            "local-root": ("hl", "local-file", "Typeclasses"),
            "cross-chapter": ("lf", "typeclasses-file", "Typeclasses"),
            "cross-nested": ("lf", "typeclasses-file", "MapLookup"),
            "cross-auto": ("lf", "typeclasses-file", "Logical-Foundations--Typeclasses--Automatic"),
            "local-nested": ("hl", "local-file", "Typeclasses"),
        }
        if draft:
            expected["cross-draft"] = ("lf", "typeclasses-file", "Draft")
        seen = set()
        for source in html_dir("hl").rglob("*.html"):
            page = Links(source)
            for label, href in page.links.items():
                if label not in expected:
                    continue
                with self.subTest(label=label, mode=mode, release=release):
                    self.assertFalse(href.startswith(("/", "http:", "https:")), href)
                    source_url = prefix + source.relative_to(site).as_posix()
                    resolved = urlsplit(urljoin(urljoin(source_url, page.base), href))
                    prefix_path = urlsplit(prefix).path
                    self.assertTrue(resolved.path.startswith(prefix_path), href)
                    target = site / unquote(resolved.path.removeprefix(prefix_path))
                    if target.is_dir():
                        target /= "index.html"
                    vol, chapter, anchor = expected[label]
                    target_dir = html_dir(vol) / chapter if depth else html_dir(vol)
                    self.assertEqual(target, target_dir / "index.html")
                    self.assertEqual(unquote(resolved.fragment), anchor)
                    destination = Links(target)
                    if not depth or label in ("cross-nested", "cross-auto", "cross-draft"):
                        self.assertIn(anchor, destination.ids)
                    else:
                        # Verso omits an id on page titles; their first permalink
                        # names the page's tag. Section anchors must exist above.
                        self.assertEqual(destination.permalinks[0], anchor)
                    seen.add(label)
        self.assertEqual(seen, expected.keys())

    def test_preview_modes(self):
        with tempfile.TemporaryDirectory(prefix="sfl-cross-volume-") as tmp:
            site = Path(tmp) / "_out"
            for mode in ("student", "solutions", "terse", "grading"):
                with self.subTest(mode=mode):
                    self.render(site, mode)
                    self.check_links(site, mode)

    def test_packaged_release(self):
        with tempfile.TemporaryDirectory(prefix="sfl-cross-volume-") as tmp:
            root = Path(tmp)
            self.render(root / "_out", layout="release")
            for vol in ("lf", "ts", "hl"):
                lean_dir = root / "_out" / vol / "student" / "lean"
                lean_dir.mkdir()
                (lean_dir / "Main.lean").write_text("-- release fixture\n")
                with patch.object(package_release, "REPO_ROOT", root):
                    package_release.copy_release(vol, root / "release", keep_lake=False)
            self.check_links(root / "release", "student", release=True)

    def test_render_depth(self):
        with tempfile.TemporaryDirectory(prefix="sfl-cross-volume-") as tmp:
            for depth in (0, 1):
                with self.subTest(depth=depth):
                    site = Path(tmp) / str(depth)
                    # The last --depth wins, as in Verso's own parser.
                    self.render(site, options=("--depth", "3", "--depth", str(depth)))
                    self.check_links(site, "student", depth=depth)

    def test_remote_fallback(self):
        with tempfile.TemporaryDirectory(prefix="sfl-cross-volume-") as tmp:
            root = Path(tmp)
            indexes = root / "indexes"
            self.render(indexes)
            remote_config = root / "remotes.json"
            remote_config.write_text(json.dumps({
                "version": 0,
                "output": str(root / "remote-cache"),
                "sources": {
                    "lf": {
                        "root": "https://example.invalid/lf/",
                        "shortName": "LF",
                        "longName": "Logical Foundations",
                        "updateFrequency": "always",
                        "sources": [{"local": str(indexes / "lf/student/html/xref.json")}],
                    },
                },
            }))
            options = ("--remote-config", str(remote_config))
            site = root / "fallback"
            self.render(site, test_case="fallback", options=options)
            links = Links(site / "hl/student/html/index.html").links
            self.assertEqual(
                links["cross-poly"], "https://example.invalid/lf/poly-file/#Poly",
            )
            self.assertFalse(links["cross-root"].startswith("https:"), links["cross-root"])
            result = self.render(root / "missing", test_case="fallback-missing", options=options)
            self.assertNotEqual(result.returncode, 0)
            self.assertIn("Missing", result.stdout + result.stderr)
            self.assertNotIn("Cross-volume reference", result.stdout + result.stderr)

    def test_draft_targets(self):
        with tempfile.TemporaryDirectory(prefix="sfl-cross-volume-") as tmp:
            root = Path(tmp)
            self.render(root / "draft", test_case="draft", options=("--draft",))
            self.check_links(root / "draft", "student", draft=True)
            result = self.render(root / "hidden", test_case="hidden-draft")
            self.assertNotEqual(result.returncode, 0)
            self.assertIn("Remote 'lf' not found for tag 'Draft'", result.stdout + result.stderr)

    def test_release_build_selects_layout(self):
        with patch.object(package_release.subprocess, "run") as run, \
                patch.object(package_release, "copy_devcontainer"):
            package_release.build_student("hl")
        render_call = run.call_args_list[2]
        self.assertEqual(render_call.args[0], ["lake", "exe", "sfl-hl", "student"])
        self.assertEqual(render_call.kwargs["env"]["SFL_HTML_LAYOUT"], "release")

    def test_missing_target_fails(self):
        with tempfile.TemporaryDirectory(prefix="sfl-cross-volume-") as tmp:
            result = self.render(Path(tmp), test_case="missing")
            self.assertNotEqual(result.returncode, 0)
            self.assertIn("Remote 'lf' not found", result.stdout + result.stderr)
            self.assertIn("Missing", result.stdout + result.stderr)

    def test_unknown_remote_fails(self):
        with tempfile.TemporaryDirectory(prefix="sfl-cross-volume-") as tmp:
            result = self.render(Path(tmp), test_case="unknown")
            self.assertNotEqual(result.returncode, 0)
            self.assertIn("Remote 'unknown' not found", result.stdout + result.stderr)


if __name__ == "__main__":
    unittest.main()
