-- This file was generated by Codex.
import SFLMeta.Run

open Verso Doc Genre Manual SFLMeta

private def part (title : String) (metadata : PartMetadata)
    (content : Array (Doc.Block Manual) := #[]) (children : Array (Part Manual) := #[]) :
    Part Manual :=
  .mk #[.text title] title (some metadata) content children

private def reference (label tag : String) (remote : Option String := none)
    (domain : Option Lean.Name := none) : Doc.Block Manual :=
  .para #[.other (Manual.Inline.ref tag domain remote) #[.text label]]

private def typeclasses : Part Manual :=
  part "Typeclasses" {
    tag := some (.provided "Typeclasses"), file := "typeclasses-file", htmlSplit := .never
  } #[] #[
    part "Lookup" { tag := some (.provided "MapLookup") },
    part "Automatic" {},
    part "Draft" { tag := some (.provided "Draft"), draft := true }
  ]

private def poly : Part Manual :=
  part "Poly" { tag := some (.provided "Poly"), file := "poly-file", htmlSplit := .never }

private def types : Part Manual :=
  part "Types" { tag := some (.provided "Types"), file := "types-file", htmlSplit := .never }

private def source : Part Manual :=
  part "Source" {} #[
    reference "cross-root" "Typeclasses" "lf",
    reference "cross-poly" "Poly" "lf",
    reference "cross-types" "Types" "ts",
    reference "local-root" "Typeclasses"
  ] #[
    part "Local Typeclasses" { tag := some (.provided "Typeclasses"), file := "local-file" }
      #[reference "cross-chapter" "Typeclasses" "lf"] #[
        part "Nested" { file := "nested-file" } #[
          reference "cross-nested" "MapLookup" "lf" (some sectionDomain),
          reference "cross-auto" "Logical-Foundations--Typeclasses--Automatic" "lf",
          reference "local-nested" "Typeclasses"
        ]
      ]
  ]

def main (args : List String) : IO UInt32 := do
  let out :: mode :: layout :: testCase :: options := args
    | throw <| IO.userError "expected output directory, mode, layout, test case, and optional flags"
  let some variant := Variant.fromString? mode
    | throw <| IO.userError s!"invalid mode: {mode}"
  setCurrVariant variant
  let chapters := [("LF", typeclasses), ("LF", poly), ("TS", types)]
  let config := { mkConfig "hl" mode "test" with
    destination := s!"{out}/hl/{mode}", extraCss := {}, extraContents := #[] }
  if testCase == "targets" then
    for vol in ["lf", "ts"] do
      let parts := chapters.filterMap fun (v, p) => if v.toLower == vol then some p else none
      let title := if vol == "lf" then "Logical Foundations" else "Type Systems"
      let doc : Part Manual := .mk #[.text title] title none #[] parts.toArray
      let targetConfig := { config with destination := s!"{out}/{vol}/{mode}" }
      let rc ← manualMain doc (options := options) (config := targetConfig)
      if rc != 0 then return rc
      renameHtmlDir targetConfig.destination
    return 0
  let mut doc := source
  if testCase == "draft" || testCase == "hidden-draft" then
    doc := { doc with content := doc.content.push (reference "cross-draft" "Draft" "lf") }
  if ["unknown", "missing"].contains testCase then
    let remote := if testCase == "unknown" then "unknown" else "lf"
    let tag := if testCase == "unknown" then "Typeclasses" else "Missing"
    doc := { doc with content := doc.content.push (reference "invalid" tag remote) }
  let release := if layout == "release" then some (System.FilePath.mk s!"{out}/../release")
    else none
  let remotes ← writeReferenceConfig "hl" mode ["LF", "TS"] out release
  let rc ← manualMain doc (options := options)
    (config := { config with remoteConfigFile := remotes })
  if rc == 0 then renameHtmlDir config.destination
  return rc
